PEN:- 240840116017

# **Practical - 3**

### **AIM:- Apply filtering, sorting, aggregation, and GroupBy operations on real-world datasets.**

**Step-1: Import pandas library.**

In [ ]:
import pandas as pd

**Step-2: Create sample data.**

In [ ]:
# Create dictionary to store employee information.
data = {
    "Emp_ID" : [101,102,103,104,105,106,107,108],
    "Name" : ["Rahul", "Priya", "Amit", "Riya", "Karan", "Neha", "Vivek", "Pooja"],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "Finance", "IT", "HR"],
    "City" : ["Surat", "Navsari", "Surat", "Valsad", "Surat", "Navsari", "Valsad", "Surat"],
    "Salary" : [45000, 38000, 52000, 48000, 40000, 51000, 60000, 42000],
    "Experience" : [2, 1, 5, 4, 2, 6, 8, 3]
}

**Step-3: Create a dataframe.**

In [ ]:
df = pd.DataFrame(data)     # Convert dictionary into pandas a dataframe.
df                          # Display thedataframe into tabular format.

   Emp_ID   Name Department     City  Salary  Experience
0     101  Rahul         IT    Surat   45000           2
1     102  Priya         HR  Navsari   38000           1
2     103   Amit         IT    Surat   52000           5
3     104   Riya    Finance   Valsad   48000           4
4     105  Karan         HR    Surat   40000           2
5     106   Neha    Finance  Navsari   51000           6
6     107  Vivek         IT   Valsad   60000           8
7     108  Pooja         HR    Surat   42000           3

**Step-4: Display the dataset.**

In [ ]:
# Display the complete dataframe
df

   Emp_ID   Name Department     City  Salary  Experience
0     101  Rahul         IT    Surat   45000           2
1     102  Priya         HR  Navsari   38000           1
2     103   Amit         IT    Surat   52000           5
3     104   Riya    Finance   Valsad   48000           4
4     105  Karan         HR    Surat   40000           2
5     106   Neha    Finance  Navsari   51000           6
6     107  Vivek         IT   Valsad   60000           8
7     108  Pooja         HR    Surat   42000           3

**Step-5: filter data.**

In [ ]:
#  Select only employees working in the IT department.
df[df["Department"]=="IT"]

   Emp_ID   Name Department    City  Salary  Experience
0     101  Rahul         IT   Surat   45000           2
2     103   Amit         IT   Surat   52000           5
6     107  Vivek         IT  Valsad   60000           8

**Task-1: Display employees whose salary is greater than 50000.**

In [ ]:
# Display employees whose salary is greater than 50000.
df[df["Salary"]>50000]

   Emp_ID   Name Department     City  Salary  Experience
2     103   Amit         IT    Surat   52000           5
5     106   Neha    Finance  Navsari   51000           6
6     107  Vivek         IT   Valsad   60000           8

**Task-2: Display employees from surat.**

In [ ]:
df[df["City"]=="Surat"]

   Emp_ID   Name Department   City  Salary  Experience
0     101  Rahul         IT  Surat   45000           2
2     103   Amit         IT  Surat   52000           5
4     105  Karan         HR  Surat   40000           2
7     108  Pooja         HR  Surat   42000           3

**Task-3: Apply multiple conditions.**

In [ ]:
# Display employees from IT department.
# having salary greater than 50000.
df[(df["Department"]=="IT") & (df["Salary"]>50000)]

   Emp_ID   Name Department    City  Salary  Experience
2     103   Amit         IT   Surat   52000           5
6     107  Vivek         IT  Valsad   60000           8

**Step-6: Sort Data.**

**Task-1: Sort salary in ascending order.**

In [ ]:
# Sort employess by salary from lowest to highest.
df.sort_values(by="Salary")

   Emp_ID   Name Department     City  Salary  Experience
1     102  Priya         HR  Navsari   38000           1
4     105  Karan         HR    Surat   40000           2
7     108  Pooja         HR    Surat   42000           3
0     101  Rahul         IT    Surat   45000           2
3     104   Riya    Finance   Valsad   48000           4
5     106   Neha    Finance  Navsari   51000           6
2     103   Amit         IT    Surat   52000           5
6     107  Vivek         IT   Valsad   60000           8

**Task-2: Sort salary in decsending order.**

In [ ]:
# sort employees by salary from highest to lowest.
df.sort_values(by="Salary", ascending=False)

   Emp_ID   Name Department     City  Salary  Experience
6     107  Vivek         IT   Valsad   60000           8
2     103   Amit         IT    Surat   52000           5
5     106   Neha    Finance  Navsari   51000           6
3     104   Riya    Finance   Valsad   48000           4
0     101  Rahul         IT    Surat   45000           2
7     108  Pooja         HR    Surat   42000           3
4     105  Karan         HR    Surat   40000           2
1     102  Priya         HR  Navsari   38000           1

**Task-3: Sort by department and salary.**

In [ ]:
# first sort by department.
# within each department, sort salaries in descending order.
df.sort_values(by=["Department", "Salary"], ascending=[True,False])

   Emp_ID   Name Department     City  Salary  Experience
5     106   Neha    Finance  Navsari   51000           6
3     104   Riya    Finance   Valsad   48000           4
7     108  Pooja         HR    Surat   42000           3
4     105  Karan         HR    Surat   40000           2
1     102  Priya         HR  Navsari   38000           1
6     107  Vivek         IT   Valsad   60000           8
2     103   Amit         IT    Surat   52000           5
0     101  Rahul         IT    Surat   45000           2

**Step-7: Perform Aggregation.**

**Task-1: Calculate total salary.**

In [ ]:
# Calculate total salary.
df["Salary"].sum()

np.int64(376000)

**Task-2: Calculate average salary.**

In [ ]:
# Calculate the avg salary.
df["Salary"].mean()

np.float64(47000.0)

**Task-3: Find highest salary.**

In [ ]:
# Display the maximum salary.
df["Salary"].max()

60000

**Task-4: Find lowest salary.**

In [ ]:
# Display the minimum salary.
df["Salary"].min()

38000

**Task-5: Count Employees.**

In [ ]:
# Count the total number of employees.
df["Emp_ID"].count()

np.int64(8)

**Step-8: Perform GroupBy Operations.**

**Task-1: Average salary department-wise.**

In [ ]:
# Group employees based on department.
# Calculate the average salary of each department.
df.groupby("Department")["Salary"].mean()

Department
Finance    49500.000000
HR         40000.000000
IT         52333.333333
Name: Salary, dtype: float64

**Task-2: Minimum salary department-wise.**

In [ ]:
# Group employees based on department.
# Calculate minimum salary of each department.
df.groupby("Department")["Salary"].min()

Department
Finance    48000
HR         38000
IT         45000
Name: Salary, dtype: int64

**Task-3: Count the total number of employees department-wise.**

In [ ]:
# Group employees based on department.
# Calculate total number of employees in each department.
df.groupby("Department")["Emp_ID"].count()

Department
Finance    2
HR         3
IT         3
Name: Emp_ID, dtype: int64

**Task-4: Total salary department-wise.**

In [ ]:
# Calculate the total salary paid by each department.
df.groupby("Department")["Salary"].sum()

Department
Finance     99000
HR         120000
IT         157000
Name: Salary, dtype: int64

**Task-5: Maximum salary department-wise.**

In [ ]:
# Calculate maximum salary of each department.
df.groupby("Department")["Salary"].max()

Department
Finance    51000
HR         42000
IT         60000
Name: Salary, dtype: int64

**Task-6: Display city-wise salary**

In [ ]:
# Group employees based on city
# Calculate average salary of employee from each city.
df.groupby("City")["Salary"].mean()

City
Navsari    44500.0
Surat      44750.0
Valsad     54000.0
Name: Salary, dtype: float64

**Step-9: Multiple aggregation functions.**

In [ ]:
# Apply multiple statistocal functions
# to the salary column for each department.
df.groupby("Department")["Salary"].agg(["count","sum", "mean", "min", "max"])

            count     sum          mean    min    max
Department
Finance         2   99000  49500.000000  48000  51000
HR              3  120000  40000.000000  38000  42000
IT              3  157000  52333.333333  45000  60000

**Step-10: Save the result.**

In [ ]:
# Save the dataset into a csv file.
df.to_csv("Employee_Data.csv", index=False)
print("Dataset saved successfully.")

Dataset saved successfully.

**Download CSV file.**

In [ ]:
# Save the dataframe as a csv file
df.to_csv("Employee_data.csv", index=False)

#import the files module from googke colab
from google.colab import files

# download the csv file to your computer
files.download("Employee_Data.csv")