**Step-1: Import the pandas library**

In [ ]:
# import pandas library.
import pandas as pd

**Step-2: Create sample data**

In [ ]:
# Create a dictionary to store student information.
data = {
    "ID": [101,102,103,104,105,106,107],
    "Name": ["Rahul", "Priya", "Amit", "Riya", "Karan", "Krisha", "Harry"],
    "Age": [20, 21, 19, 20, 22, 24, 28],
    "City": ["Surat", "Navsari", "Valsad", "Bharuch", "Surat", "Gadhinagar", "Ahmedabad"],
    "Marks": [85, 92, 78, 88, 81, 84, 90]
}

**Step-3: Create a dataframe**

In [ ]:
df = pd.DataFrame(data)    # Convert the dictionary into a Pandas DataFrame.
df                         # Display the DataFrame in tabular format.

    ID    Name  Age        City  Marks
0  101   Rahul   20       Surat     85
1  102   Priya   21     Navsari     92
2  103    Amit   19      Valsad     78
3  104    Riya   20     Bharuch     88
4  105   Karan   22       Surat     81
5  106  Krisha   24  Gadhinagar     84
6  107   Harry   28   Ahmedabad     90

**Step-4: Save data as a csv file**

In [ ]:
df.to_csv("students.csv", index=False)        # Save the DataFrame as a CSV file.
print("CSV file created successfully")        # Display confirmation after saving the file.

CSV file created successfully

**Step-5: Save data as an excel file**

In [ ]:
df.to_excel("students.xlsx", index=False)        # Save the DataFrame as an Excel file.
print("Excel file created successfully")         # Display confirmation message.

Excel file created successfully

**Step-6: Save data as a json file**

In [ ]:
df.to_json("students.json", orient="records", indent=4)  # Save the DataFrame as a formatted json file.
print("JSON file created successfully")                  # Display confirmation message.

JSON file created successfully

**Step-7: Read the csv file**

In [ ]:
df_csv = pd.read_csv("students.csv")     # Load data from the CSV file into a DataFrame.
df_csv                                   # Display the loaded data.

    ID    Name  Age        City  Marks
0  101   Rahul   20       Surat     85
1  102   Priya   21     Navsari     92
2  103    Amit   19      Valsad     78
3  104    Riya   20     Bharuch     88
4  105   Karan   22       Surat     81
5  106  Krisha   24  Gadhinagar     84
6  107   Harry   28   Ahmedabad     90

**Step-8: Read the excel file**

In [ ]:
df_excel = pd.read_excel("students.xlsx")     # Load data from the Excel file.
df_excel                                      # Display the loaded DataFrame.

    ID    Name  Age        City  Marks
0  101   Rahul   20       Surat     85
1  102   Priya   21     Navsari     92
2  103    Amit   19      Valsad     78
3  104    Riya   20     Bharuch     88
4  105   Karan   22       Surat     81
5  106  Krisha   24  Gadhinagar     84
6  107   Harry   28   Ahmedabad     90

**Step-9: Read the json file**

In [ ]:
df_json = pd.read_json("students.json")       # Load data from the JSON file.
df_json                                       # Display the loaded DataFrame.

    ID    Name  Age        City  Marks
0  101   Rahul   20       Surat     85
1  102   Priya   21     Navsari     92
2  103    Amit   19      Valsad     78
3  104    Riya   20     Bharuch     88
4  105   Karan   22       Surat     81
5  106  Krisha   24  Gadhinagar     84
6  107   Harry   28   Ahmedabad     90

**Step-10: Display the first five records**

In [ ]:
df_csv.head()      # Returns the first five rows of the DataFrame by default.

    ID   Name  Age     City  Marks
0  101  Rahul   20    Surat     85
1  102  Priya   21  Navsari     92
2  103   Amit   19   Valsad     78
3  104   Riya   20  Bharuch     88
4  105  Karan   22    Surat     81

**Step-11: Display the last five records**

In [ ]:
df_csv.tail()      # Returns the last five rows of the DataFrame by default.

    ID    Name  Age        City  Marks
2  103    Amit   19      Valsad     78
3  104    Riya   20     Bharuch     88
4  105   Karan   22       Surat     81
5  106  Krisha   24  Gadhinagar     84
6  107   Harry   28   Ahmedabad     90

**Step-12: Display dataset information**

In [ ]:
# Display a summary of the DataFrame.
df_csv.info()

# info() displays:
# -numbers of rows and columns
# -datatype
# -memory usage

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      7 non-null      int64
 1   Name    7 non-null      object
 2   Age     7 non-null      int64
 3   City    7 non-null      object
 4   Marks   7 non-null      int64
dtypes: int64(3), object(2)
memory usage: 412.0+ bytes

**Step-13: Display the statistical summary**

In [ ]:
# Generate descriptive statistics for numerical columns.
df_csv.describe()

#describe() displays:
#count
#mean
#std
#min
#max
#25%,50%,75% percentiles

               ID        Age      Marks
count    7.000000   7.000000   7.000000
mean   104.000000  22.000000  85.428571
std      2.160247   3.109126   4.961759
min    101.000000  19.000000  78.000000
25%    102.500000  20.000000  82.500000
50%    104.000000  21.000000  85.000000
75%    105.500000  23.000000  89.000000
max    107.000000  28.000000  92.000000

**Step-14: Display dataset shape**

In [ ]:
# Return the dimensions of the DataFrame as (rows, columns).

df_csv.shape

(7, 5)

**Step-15: Display column names**

In [ ]:
# Return the names of all columns in the DataFrame.
df_csv.columns

Index(['ID', 'Name', 'Age', 'City', 'Marks'], dtype='object')

**Step-16: Display data types**

In [ ]:
# Return the data type of every column.
df_csv.dtypes

ID        int64
Name     object
Age       int64
City     object
Marks     int64
dtype: object

**Step-17: Check for missing values**

In [ ]:
# Count the number of missing (null) values in each column.
df_csv.isnull().sum()

ID       0
Name     0
Age      0
City     0
Marks    0
dtype: int64

**Step-18: Display a single column**

In [ ]:
 # Select and display only the 'Marks' column.
df_csv["Marks"]

0    85
1    92
2    78
3    88
4    81
5    84
6    90
Name: Marks, dtype: int64

**Step-19: Display multiple column**

In [ ]:
 # Select and display multiple specified columns.
df_csv[["Name", "Marks"]]

     Name  Marks
0   Rahul     85
1   Priya     92
2    Amit     78
3    Riya     88
4   Karan     81
5  Krisha     84
6   Harry     90

**Step-20: Filter records**

In [ ]:
# Display only students whose marks are greater than 80.
df_csv[df_csv["Marks"] > 80]

    ID    Name  Age        City  Marks
0  101   Rahul   20       Surat     85
1  102   Priya   21     Navsari     92
3  104    Riya   20     Bharuch     88
4  105   Karan   22       Surat     81
5  106  Krisha   24  Gadhinagar     84
6  107   Harry   28   Ahmedabad     90

**Step-21: Calculate average marks**

In [ ]:
# Calculate and return the average marks of all students.
df_csv["Marks"].mean()

np.float64(85.42857142857143)

**Step-22: Sort data**

In [ ]:
# Sort the dataset in descending order of marks.

df_csv.sort_values(by="Marks", ascending=False)

    ID    Name  Age        City  Marks
1  102   Priya   21     Navsari     92
6  107   Harry   28   Ahmedabad     90
3  104    Riya   20     Bharuch     88
0  101   Rahul   20       Surat     85
5  106  Krisha   24  Gadhinagar     84
4  105   Karan   22       Surat     81
2  103    Amit   19      Valsad     78