**Step-1: Import the pandas Library**

In [ ]:
import pandas as pd

**Step-2: Create sample data**

In [ ]:
# Create a dictionary to store student information.
data = {
    "ID": [101,102,103,104,105,106,107,108],
    "Name": ["Rahul", "Priya", "Amit", "Riya", "Karan", "Krisha", "Harry","Aman"],
    "Age": [20, 21, None, 20, 20, 22, 23,20],
    "City": ["Surat", "Navsari", "Surat", "Bharuch", "Bharuch", "Navsari", "Surat", "Ahmedabad"],
    "Marks": [85, None, 78, 88, 88, 81, 90, 93]
}

**Step-3: Create a dataframe**

In [ ]:
df = pd.DataFrame(data)    # Convert the dictionary into a Pandas DataFrame.
df                         # Display the DataFrame in tabular format.

    ID    Name   Age       City  Marks
0  101   Rahul  20.0      Surat   85.0
1  102   Priya  21.0    Navsari    NaN
2  103    Amit   NaN      Surat   78.0
3  104    Riya  20.0    Bharuch   88.0
4  105   Karan  20.0    Bharuch   88.0
5  106  Krisha  22.0    Navsari   81.0
6  107   Harry  23.0      Surat   90.0
7  108    Aman  20.0  Ahmedabad   93.0

**Step-4: Inspect the dataset.**

In [ ]:
# Display first five row of dataset.
df.head()

    ID   Name   Age     City  Marks
0  101  Rahul  20.0    Surat   85.0
1  102  Priya  21.0  Navsari    NaN
2  103   Amit   NaN    Surat   78.0
3  104   Riya  20.0  Bharuch   88.0
4  105  Karan  20.0  Bharuch   88.0

In [ ]:
# Display last five row of dataset.
df.tail()

    ID    Name   Age       City  Marks
3  104    Riya  20.0    Bharuch   88.0
4  105   Karan  20.0    Bharuch   88.0
5  106  Krisha  22.0    Navsari   81.0
6  107   Harry  23.0      Surat   90.0
7  108    Aman  20.0  Ahmedabad   93.0

In [ ]:
# Display detailed information about dataset.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      8 non-null      int64
 1   Name    8 non-null      object
 2   Age     7 non-null      float64
 3   City    8 non-null      object
 4   Marks   7 non-null      float64
dtypes: float64(2), int64(1), object(2)
memory usage: 452.0+ bytes

In [ ]:
# Generate statistical information.
df.describe()

              ID        Age      Marks
count    8.00000   7.000000   7.000000
mean   104.50000  20.857143  86.142857
std      2.44949   1.214986   5.209881
min    101.00000  20.000000  78.000000
25%    102.75000  20.000000  83.000000
50%    104.50000  20.000000  88.000000
75%    106.25000  21.500000  89.000000
max    108.00000  23.000000  93.000000

In [ ]:
# Display dimension of dataset.
df.shape       # Output Format: (Number of rows, Number of columns)

(8, 5)

In [ ]:
# Display the name of all columns.
df.columns

Index(['ID', 'Name', 'Age', 'City', 'Marks'], dtype='object')

In [ ]:
# Display the data type of each column.
df.dtypes

ID         int64
Name      object
Age      float64
City      object
Marks    float64
dtype: object

**Step-5: Check missing values.**

In [ ]:
# Check for missing value(NULL) in every column.
df.isnull().sum()

ID       0
Name     0
Age      1
City     0
Marks    1
dtype: int64

**Step-6: Fill missing values.**

In [ ]:
# Fill missing marks.
# Replace missing value in marks column.
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())
df
# fillna() replace missing values with average.

    ID    Name   Age       City      Marks
0  101   Rahul  20.0      Surat  85.000000
1  102   Priya  21.0    Navsari  86.142857
2  103    Amit   NaN      Surat  78.000000
3  104    Riya  20.0    Bharuch  88.000000
4  105   Karan  20.0    Bharuch  88.000000
5  106  Krisha  22.0    Navsari  81.000000
6  107   Harry  23.0      Surat  90.000000
7  108    Aman  20.0  Ahmedabad  93.000000

In [ ]:
# Fill missing age.
# Using the average age of all student.
# Replace missing value in age column.

df["Age"] = df["Age"].fillna(df["Age"].mean())
df

    ID    Name        Age       City      Marks
0  101   Rahul  20.000000      Surat  85.000000
1  102   Priya  21.000000    Navsari  86.142857
2  103    Amit  20.857143      Surat  78.000000
3  104    Riya  20.000000    Bharuch  88.000000
4  105   Karan  20.000000    Bharuch  88.000000
5  106  Krisha  22.000000    Navsari  81.000000
6  107   Harry  23.000000      Surat  90.000000
7  108    Aman  20.000000  Ahmedabad  93.000000

In [ ]:
# Fill missing names.
# Replace missing names with the text "Unknown".

df["Name"] = df["Name"].fillna("Unknown")
df

    ID    Name        Age       City      Marks
0  101   Rahul  20.000000      Surat  85.000000
1  102   Priya  21.000000    Navsari  86.142857
2  103    Amit  20.857143      Surat  78.000000
3  104    Riya  20.000000    Bharuch  88.000000
4  105   Karan  20.000000    Bharuch  88.000000
5  106  Krisha  22.000000    Navsari  81.000000
6  107   Harry  23.000000      Surat  90.000000
7  108    Aman  20.000000  Ahmedabad  93.000000

**Step-7: Detect duplicate records.**

In [ ]:
# Check whether each row is duplicate.
df.duplicated()

# True indicates a duplicate row.
# False indicates a unique row.

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
dtype: bool

In [ ]:
# Count the total number of duplicate row.
df.duplicated().sum()

np.int64(0)

**Step-8: Remove duplicate records.**

In [ ]:
# Remove duplicate rows from dataframe.
df = df.drop_duplicates()          # removes repeated rows and retains only the first occurence.
df

    ID    Name        Age       City      Marks
0  101   Rahul  20.000000      Surat  85.000000
1  102   Priya  21.000000    Navsari  86.142857
2  103    Amit  20.857143      Surat  78.000000
3  104    Riya  20.000000    Bharuch  88.000000
4  105   Karan  20.000000    Bharuch  88.000000
5  106  Krisha  22.000000    Navsari  81.000000
6  107   Harry  23.000000      Surat  90.000000
7  108    Aman  20.000000  Ahmedabad  93.000000

**Step-9: Rename a column.**

In [ ]:
# Rename the column "Marks" to "Score".
df.rename(columns = {"Marks" : "Score"}, inplace=True)
df

    ID    Name        Age       City      Score
0  101   Rahul  20.000000      Surat  85.000000
1  102   Priya  21.000000    Navsari  86.142857
2  103    Amit  20.857143      Surat  78.000000
3  104    Riya  20.000000    Bharuch  88.000000
4  105   Karan  20.000000    Bharuch  88.000000
5  106  Krisha  22.000000    Navsari  81.000000
6  107   Harry  23.000000      Surat  90.000000
7  108    Aman  20.000000  Ahmedabad  93.000000

**Srep-10: Change the data type.**

In [ ]:
# Convert each column from float to integer.
df["Age"] = df["Age"].astype(int)
df.dtypes

ID         int64
Name      object
Age        int64
City      object
Score    float64
dtype: object

**Step-11: Create a new column.**

In [ ]:
# Create a new column named "Final Score".
df["Final Score"] = df["Score"] + 5         # Add 5 grace marks to every student's score.
df

    ID    Name  Age       City      Score  Final Score
0  101   Rahul   20      Surat  85.000000    90.000000
1  102   Priya   21    Navsari  86.142857    91.142857
2  103    Amit   20      Surat  78.000000    83.000000
3  104    Riya   20    Bharuch  88.000000    93.000000
4  105   Karan   20    Bharuch  88.000000    93.000000
5  106  Krisha   22    Navsari  81.000000    86.000000
6  107   Harry   23      Surat  90.000000    95.000000
7  108    Aman   20  Ahmedabad  93.000000    98.000000

**Step-12: Convert text to uppercase.**

In [ ]:
# Convert all student names to uppercase.
df["Name"] = df["Name"].str.upper()
df

    ID    Name  Age       City      Score  Final Score
0  101   RAHUL   20      Surat  85.000000    90.000000
1  102   PRIYA   21    Navsari  86.142857    91.142857
2  103    AMIT   20      Surat  78.000000    83.000000
3  104    RIYA   20    Bharuch  88.000000    93.000000
4  105   KARAN   20    Bharuch  88.000000    93.000000
5  106  KRISHA   22    Navsari  81.000000    86.000000
6  107   HARRY   23      Surat  90.000000    95.000000
7  108    AMAN   20  Ahmedabad  93.000000    98.000000

**Step-13: Convert text to lowecase.**

In [ ]:
# Convert all city names to lowercase.
df["City"] = df["City"].str.lower()
df

    ID    Name  Age       City      Score  Final Score
0  101   RAHUL   20      surat  85.000000    90.000000
1  102   PRIYA   21    navsari  86.142857    91.142857
2  103    AMIT   20      surat  78.000000    83.000000
3  104    RIYA   20    bharuch  88.000000    93.000000
4  105   KARAN   20    bharuch  88.000000    93.000000
5  106  KRISHA   22    navsari  81.000000    86.000000
6  107   HARRY   23      surat  90.000000    95.000000
7  108    AMAN   20  ahmedabad  93.000000    98.000000

Step-14: Remove extra spaces.

In [ ]:
# Remove leading and trailing spaces from city names.
df["City"] = df["City"].str.strip()
df

    ID    Name  Age       City      Score  Final Score
0  101   RAHUL   20      surat  85.000000    90.000000
1  102   PRIYA   21    navsari  86.142857    91.142857
2  103    AMIT   20      surat  78.000000    83.000000
3  104    RIYA   20    bharuch  88.000000    93.000000
4  105   KARAN   20    bharuch  88.000000    93.000000
5  106  KRISHA   22    navsari  81.000000    86.000000
6  107   HARRY   23      surat  90.000000    95.000000
7  108    AMAN   20  ahmedabad  93.000000    98.000000

**Step-15: Sort the dataset.**

In [ ]:
# Sort the dataframe based on "Final Score" column.
df.sort_values(by= "Final Score", ascending=False)

    ID    Name  Age       City      Score  Final Score
7  108    AMAN   20  ahmedabad  93.000000    98.000000
6  107   HARRY   23      surat  90.000000    95.000000
3  104    RIYA   20    bharuch  88.000000    93.000000
4  105   KARAN   20    bharuch  88.000000    93.000000
1  102   PRIYA   21    navsari  86.142857    91.142857
0  101   RAHUL   20      surat  85.000000    90.000000
5  106  KRISHA   22    navsari  81.000000    86.000000
2  103    AMIT   20      surat  78.000000    83.000000

**Step-16: Save the cleaned dataset.**

In [ ]:
# Save the cleaned dataframe as a new CSV file.
df.to_csv("cleaned_students.csv", index=False)
print("Dataset saved successfully.")

Dataset saved successfully.